book/urls.py
from django.urls import path
from .views import home,book_detail,add_book,my_books,delete_book


urlpatterns = [
    path('',home,name='home'),
    path('book/<str:book_id>',book_detail, name="book_detail"),
    path('book/add/<str:book_id>',add_book,name="add_book"),
    path('my_books',my_books,name="my_books"),
    path('book/<str:book_id>/delete',delete_book,name="delete_book")
]

google_books/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('book.urls')),
    path('accounts/',include('user.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models

from django.contrib.auth.models import User


READ_STATUS = (
    ('R','Read'),
    ('W','Want To Read'),
    ('C','Currently Reading')
)

class Books(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    book_id = models.CharField(max_length=30,unique=True)
    title = models.CharField(null=True,blank=True,max_length=100)
    author = models.CharField(null=True,blank=True,max_length=100)
    description = models.TextField(null=True,blank=True)
    read_status = models.CharField(choices=READ_STATUS,max_length=2)
    page_count = models.CharField(max_length=6,null=True,blank=True)
    image_url = models.CharField(max_length=50,blank=True, null=True)
    average_rating = models.CharField(max_length=20,null=True,blank=True)
    date_created = models.DateField(auto_now=False,auto_now_add=True)
    date_updated = models.DateField(auto_now=True,auto_now_add=False)

book/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView
from django.conf import settings
from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.contrib import messages
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Books


import requests
import math


def home(request):
    #PAGINATION

    #if page_number did not assigned return homepage 
    page_number = 1
    try:
        page_number = int(request.GET.get('page'))
    except:
        pass

    ##increment and decrement next and previous page
    next_page_number = page_number +1
    previous_page_number = page_number -1

    #if page_number less than 1 raise 404 Error
    if page_number < 1:
        raise Http404

    books = []
    if request.method=="POST":
        q = request.POST.get('q')
        maxResult = 12
        startIndex = (page_number-1)*maxResult
        search_url = f'https://www.googleapis.com/books/v1/volumes?q={q}'
        params = {
            'key':settings.GOOGLE_BOOKS_API_KEY,
            'printType':'books',
            'orderBy':'relevance',
            'maxResults':maxResult,
            'startIndex':startIndex
        }
        
        r = requests.get(search_url,params=params).json()
        try:
            for i in range(len(r['items'])):
                info = r['items'][i]['volumeInfo']
                book_info = {
                    'id':r['items'][i]['id'],
                    'title':info['title'],
                    'author':info['authors'][0] if 'authors' in info else '' ,
                    'publisher':info['publisher'] if 'publisher' in info else '',
                    'pageCount':info.get('publisher'),
                    'thumbnail':info['imageLinks']['smallThumbnail'] if 'imageLinks' in info else 'http://placehold.jp/128x192.png',
                    'totalItems':r['totalItems']
                    
                }
                books.append(book_info)
        except KeyError:
            if q != "":
                messages.error(request,"There is no more page for this book")
            else:
                messages.info(request,"Search field can't be empty")

    q_value =request.POST.get('q')
    context = {
        'books':books,
        'q_value':q_value,
        'page_number':page_number,
        'next_page_number':next_page_number,
        'previous_page_number':previous_page_number,
    }
    return render(request,'book/home.html',context)




def book_detail(request,book_id):
    book = None
    try:
        book = Books.objects.get(book_id=book_id,user=request.user)
    except:
        pass
    detail_url = f'https://www.googleapis.com/books/v1/volumes/{book_id}'
    r = requests.get(detail_url).json()
    context = {
        'id' : r['id'],
        'title':r['volumeInfo']['title'],
        'image':r['volumeInfo']['imageLinks']['thumbnail'],
        'author':r['volumeInfo']['authors'][0],
        'publisher':r['volumeInfo']['publisher'],
        'description':r['volumeInfo']['description'] if 'description' in r['volumeInfo'] else 'No Description',
        'average_rating':r['volumeInfo']['averageRating'] if 'averageRating' in r['volumeInfo'] else '',
        'ratings_count':r['volumeInfo']['ratingsCount'] if 'ratingsCount' in r['volumeInfo'] else '',
        'isbn':r['volumeInfo']['industryIdentifiers'][1]['identifier'] if 'industryIdentifiers' in r['volumeInfo'] else 'No Isbn',
        'language':r['volumeInfo']['language'],
        'pageCount':r['volumeInfo'].get('pageCount'),
        'publisher':r['volumeInfo'].get('publisher'),
        'publishedDate':r['volumeInfo'].get('publishedDate'),
        'book':book
    }

    return render(request,'book/book_detail.html',context)




def add_book(request,book_id):
    read_status = request.GET.get('read_status')
    book = Books.objects.filter(user=request.user,book_id=book_id)
    if book.exists():
        _book = Books.objects.get(book_id=book_id)
        _book.read_status = read_status
        _book.save()
    else:
        url = f'https://www.googleapis.com/books/v1/volumes/{book_id}'
        r = requests.get(url).json()
        user = request.user
        title = r['volumeInfo']['title']
        author = r['volumeInfo']['authors'][0]
        description = r['volumeInfo']['description']  if 'description' in r['volumeInfo'] else 'No Description'
        page_count = r['volumeInfo'].get('pageCount')
        image_url = r['volumeInfo']['imageLinks']['smallThumbnail']
        average_rating = r['volumeInfo']['averageRating'] if 'averageRating' in r['volumeInfo'] else '';

        Books.objects.create(
            user=user,
            book_id=book_id,
            title=title,
            author=author,
            description = description,
            read_status = read_status,
            page_count = page_count,
            image_url = image_url,
            average_rating = average_rating
        )
    return JsonResponse({'read_status':read_status})

    
@login_required   
def my_books(request):
    books = Books.objects.filter(user=request.user)
    return render(request,'book/my_books.html',{'books':books})


def delete_book(request,book_id):
    book_id = request.GET.get('id')
    book = get_object_or_404(Books,book_id=book_id,user=request.user)
    book.delete()
    _book = model_to_dict(book)
    return JsonResponse({'book_id':book.id,'book':_book})

templates/book/book_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-4">
    <div class="row">
        <div class="col-md-4">
            <img src="{{image}}" alt="{{ title}}-thumbnail">
            <hr>
            {% if average_rating %}
            <div>
                <div class="stars-outer">
                    <div class="stars-inner"></div>
                </div>
                <span class="number-rating">{{ average_rating }}</span>
                <span>({{ ratings_count}} ratings)</span>
            </div>
            {% endif %}
            {% if user.is_authenticated %}
            <form>
                <select id="read_status" name="read_status" onchange="get_read_status()">
                    <option>---</option>
                    <option id="R" {% if book.read_status == "R" %}  selected {% endif %}
                        value="R">
                        {% if book.read_status == "R" %}
                        &#xf00c;
                        {% endif %}
                        Read
                    </option>
                    <option id="W" {% if book.read_status == "W" %} selected {% endif %} value="W">
                        {% if book.read_status == "W" %}
                        &#xf00c;
                        {% endif %}
                        Want to Read
                    </option>
                    <option id="C" {% if book.read_status == "C" %} selected {% endif %} value="C">
                        {% if book.read_status == "C" %}
                        &#xf00c;
                        {% endif %}
                        Currently Reading
                    </option>
                </select>
            </form>
            {% endif %}
        </div>
        <div class="col-md-8">
            <h2>{{title}}</h2>
            <hr>
            <div class="book-detail-info">
                <p class="text-muted">{{ author }}</p>
                <p class="text-muted">{{ publisher }}</p>
            </div>
            <p>{{ description }}</p>

            <!--BOOK INFO-->
            <h4>Book Informations</h4>
            <hr>
            <div class="floats">
                <div class="info-title">Original Title</div>
                <div class="info-item">{{title}}</div>
            </div>
            {% if isbn %}
            <div class="floats">
                <div class="info-title">ISBN</div>
                <div class="info-item">{{isbn}}</div>
            </div>
            {% endif %}
            {% if language %}
            <div class="floats">
                <div class="info-title">Language</div>
                <div class="info-item">{{language}}</div>
            </div>
            {% endif %}
            {% if pageCount %}
            <div class="floats">
                <div class="info-title">Number Of Pages</div>
                <div class="info-item">{{pageCount}}</div>
            </div>
            {% endif %}
            {% if publisher %}
            <div class="floats">
                <div class="info-title">Publisher</div>
                <div class="info-item">{{publisher}}</div>
            </div>
            {% endif %}
            {% if publishedDate %}
            <div class="floats">
                <div class="info-title">Publish Date</div>
                <div class="info-item">{{publishedDate}}</div>
            </div>
            {% endif %}
        </div>
    </div>
</div>


<script>
    //STAR
    const starsTotal = 5;

    rating = document.querySelector('.number-rating').innerHTML;


    document.addEventListener('DOMContentLoaded', getRatings)

    //Get Ratings
    function getRatings() {
        const starPercentage = (rating / starsTotal) * 100;


        const starPercentageRounded = `${Math.round(starPercentage/10)*10}%`
        console.log(starPercentageRounded)

        //Set width of stars-inner to percentage
        document.querySelector('.stars-inner').style.width = starPercentageRounded;
    }




    function get_read_status() {
        $.ajax({
            url: "{% url  'add_book' id %}",
            data: {
                'read_status': $('#read_status').val()
            },
            success: function (data) {
                console.log(data)
                console.log($('#R').html())
                if (data.read_status == "R") {

                    $('#W').html('Want to Read');
                    $('#C').html('Currenly Reading');
                    $('#R').html(' &#xf00c;   Read ');

                } else if (data.read_status == "W") {

                    $('#R').html('Read');
                    $('#C').html('Currenly Reading');
                    $('#W').html(' &#xf00c;   Want to Read  ');

                } else if (data.read_status == "C") {

                    $('#W').html('Want to Read');
                    $('#R').html('Read');
                    $('#C').html(' &#xf00c;   Currently Reading ');
                }
            }
        })
    }
</script>

{% endblock content %}

templates/book/home.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 my-4  mx-auto">
            <h1 class="text-center">Search Books</h1>
            <form method="POST">{% csrf_token %}
                <div class="form-group text-center">
                    <input class="search-input" type="text" name="q" id="search-input"
                        placeholder="Search Books by Title, Author or ISBN">
                    <button class="primary-btn" type="submit">Search</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        {% for book in books %}
        {{ startIndexes}}
        <div class="col-md-3 my-3">
            <div class="card  d-flex align-items-stretch custom-card">
                <div class="imageLink text-center">
                    <a href="{% url 'book_detail'  book.id %}"><img src="{{ book.thumbnail }}" alt=""></a>
                </div>
                <div class="book-info">
                    <p class="card-text text-center">{{book.title }}</p>
                    <p class="text-muted">{{book.author}}</p>
                    <p>{{book.publisher}} </p>
                </div>
            </div>
        </div>
        {% endfor %}


        {% if request.method == "POST" %}
        {%  if books %}
        <div class="pagination">
            {% if previous_page_number %}
            <form class="pagination-form" action='{% url "home"  %}?page={{previous_page_number}}' method="POST">
                {% csrf_token %}
                <div class="form-group text-center">
                    <input class="search-input" type="hidden" value="{{q_value}}" name="q" id="search-input"
                        placeholder="Search Books by Title, Author or ISBN">
                    <button class="pagination-btn" type="submit">&laquo;</button>
                </div>
            </form>
            {% endif %}
            <li class="page-item active">
                <button class="pagination-btn" class="page-link">{{ page_number }}</button>
            </li>
            <form class="pagination-form" action='{% url "home"  %}?page={{ next_page_number }}' method="POST">
                {% csrf_token %}
                <div class="form-group text-center">
                    <input class="search-input" type="hidden" value="{{q_value}}" name="q" id="search-input"
                        placeholder="Search Books by Title, Author or ISBN">
                    <button class="pagination-btn" type="submit">&raquo;</button>
                </div>
            </form> 
        </div>
        {% endif %}
        {% endif %}



    </div>
</div>



{% endblock content %}

templates/book/my_books.html
{% extends 'base.html' %}
{% block content %}


<div class="container my-4">
    <h3>My Books</h3>
    <hr>
    <button id="general" class=" primary-btn">General Table</button>
    <button id="read" class=" primary-btn">Reading List</button>
    <button id="to_read" class="primary-btn">To Read</button>
    <button id="cur_read" class="primary-btn">Currently Reading</button>
    <!--GENERAL-->
    <div class="general my-4">
        {% if not books.all %}
        <p>There is no book in your list</p>
        {% else %}
        <table class="table gen-table ">
            <thead>
                <tr class="row-title">
                    <th scope="col">#</th>
                    <th scope="col">Cover</th>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Number Of Pages</th>
                    <th scope="col">Reading Date</th>
                    <th scope="col">Status</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}

                <tr id="book-table-{{book.book_id}}">

                    <th scope="row">{{ forloop.counter }}</th>
                    <td><img src="{{ book.image_url }}" alt="cover"></td>
                    <td><a href="{% url 'book_detail' book.book_id %}">{{ book.title }}</a></td>
                    <td>{{book.author}}</td>
                    <td>{{ book.page_count }}</td>
                    <td>{{book.date_updated}}</td>
                    <td>{{ book.get_read_status_display }}</td>
                    <td><a class="delete-btn" id="{{ book.book_id }}" onclick="deleteBook('{{book.book_id}}')"
                        data-url="{% url 'delete_book' book.book_id %}">&times;</a></td>

                </tr>

                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>

    <!--READ-->
    <div class="reading" style="display: none;">
        <table class="table ">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Cover</th>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Number Of Pages</th>
                    <th scope="col">Reading Date</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                {% if book.read_status == "R" %}
                <tr id="book-table-{{book.book_id}}">

                    <th scope="row">{{ forloop.counter }}</th>
                    <td><img src="{{ book.image_url }}" alt="cover"></td>
                    <td><a href="{% url 'book_detail' book.book_id %}">{{ book.title }}</a></td>
                    <td>{{book.author}}</td>
                    <td>{{ book.page_count }}</td>
                    <td>{{book.date_updated}}</td>
                    <td>{{ book.get_read_status_display }}</td>
                    <td></td>

                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!--TO READ-->
    <div class="to-read" style="display: none;">
        <table class="table  ">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Cover</th>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Number Of Pages</th>
                    <th scope="col">Reading Date</th>
                    <th scope="col">Status</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                {% if book.read_status == "W" %}
                <tr id="book-table-{{book.book_id}}">

                    <th scope="row">{{ forloop.counter }}</th>
                    <td><img src="{{ book.image_url }}" alt="cover"></td>
                    <td><a href="{% url 'book_detail' book.book_id %}">{{ book.title }}</a></td>
                    <td>{{book.author}}</td>
                    <td>{{ book.page_count }}</td>
                    <td>{{book.date_updated}}</td>
                    <td>{{ book.get_read_status_display }}</td>
                    <td></td>

                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!--CURRENTLY READ-->
    <div class="cur-read" style="display: none;">
        <table class="table   ">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Cover</th>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Number Of Pages</th>
                    <th scope="col">Reading Date</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                {% if book.read_status == "C" %}
                <tr id="book-table-{{book.book_id}}">

                    <th scope="row">{{ forloop.counter }}</th>
                    <td><img src="{{ book.image_url }}" alt="cover"></td>
                    <td><a href="{% url 'book_detail' book.book_id %}">{{ book.title }}</a></td>
                    <td>{{book.author}}</td>
                    <td>{{ book.page_count }}</td>
                    <td>{{book.date_updated}}</td>
                    <td>{{ book.get_read_status_display }}</td>
                    <td></td>

                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>



</div>

<script>

    document.getElementById('general').addEventListener('click',function(){
        getDisplay('general')
        getHide('to-read','cur-read','reading')
    })


    document.getElementById('read').addEventListener('click', function () {
        getDisplay('reading')
        getHide('general','to-read','cur-read') 



    })
    document.getElementById('to_read').addEventListener('click', function () {
        getDisplay('to-read')
        getHide('general','reading','cur-read') 


    })
    document.getElementById('cur_read').addEventListener('click', function () {
       
        getDisplay('cur-read')
        getHide('general','to-read','reading') 


    })


    function getDisplay(el) {
        document.querySelector(`.${el}`).style.display = 'block'
    }

    function getHide(el1,el2,el3){
        document.querySelector(`.${el1}`).style.display = "none";
        document.querySelector(`.${el2}`).style.display = "none";
        document.querySelector(`.${el3}`).style.display = "none";

    }



    //Delete Book
 
    function deleteBook(id) {
        console.log($(`#${id}`))
        $.ajax({
            url: $(`#${id}`).data('url'),
            data: {
                'id': id
            },
            success: function (data) {
                $(`#book-table-${data.book.book_id}`).html('');
                console.log(data);



            }
        })
    }
</script>

{% endblock content %}